[package]
name = "alter"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.12.0"
dirs = "6.0.0"
gix-config = "0.48.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9.8"
uuid = { version = "1", features = ["serde"] }
